### ISSUE TITLE
Reorder the lists alphabetically and check it in a CI workflow

### ISSUE THREAD

**Issue by jond01** [lirantal/awesome-opensource-israel#105]
1. reorder the lists alphabetically
2. add a markdown linter that checks for this as part of a CI
3. update the [contribution guide](https://github.com/lirantal/awesome-opensource-israel/blob/master/CONTRIBUTING.md#contribution-guidelines) accordingly

_Originally posted by @lirantal in https://github.com/lirantal/awesome-opensource-israel/issues/104#issuecomment-1416858998_

**Comment by jond01** [comment]
@lirantal, which option do you prefer:
1. [pre-commit.ci](https://pre-commit.ci/) - no workflow file needed, just `.pre-commit-config.yaml`.
  We can add other [supported hooks](https://pre-commit.com/hooks.html), such as `trailing-whitespace`, which may create automatic fixes for PRs.
  Free for open source repos but requires registration - probably on your account.
2. A standard GitHub workflow.

Irrespective of the choice, I plan to add a short Python script that checks the order for the lists we want to sort alphabetically.

**Comment by lirantal** [comment]
Thanks for researching that @jond01 🆗 

I'm in favor for a GitHub workflow because it makes it easier on this big contributors repo to avoid a single vendor and the permissions needed to set it up (which is what it seems like with the pre-commit.ci service). At the same time, happy to follow your advice for which you think is best.

**Comment by jond01** [comment]
Yes, I agree that's a good point for a GitHub workflow, then let's go for it
